
The advantages of using APIs:
 *   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more      
     productive.
 *   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to 
     independently implement some functionality from scratch.
 
The disadvantage of using APIs:
 *   **Security**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data breaches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation#intro) can be found here.

Another example of simple API we will use in this notebook is Fruityvice application. The Fruityvice API web service which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The web service is completely free to use and contribute to.

## Example 1: RandomUser API
Below are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation) page.

## **Get Methods**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

In [1]:
!pip install randomuser==1.6
!pip install pandas

Collecting randomuser==1.6
  Downloading randomuser-1.6.tar.gz (5.0 kB)
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py): started
  Building wheel for randomuser (setup.py): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5082 sha256=a0e83d93da1c8de3db2442276b6f636f03e8461c036c05bc3daa4833ec890f09
  Stored in directory: c:\users\sukru\appdata\local\pip\cache\wheels\41\6f\23\878c103a235dc2d4e85a3965c124aae8a28470c541b81aa2ba
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Requirement already satisfied: pandas in c:\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in c:\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
from randomuser import RandomUser
import pandas as pd

In [29]:
r = RandomUser()

In [30]:
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x22173df9a00>,
 <randomuser.RandomUser at 0x22173e37370>,
 <randomuser.RandomUser at 0x22173e373d0>,
 <randomuser.RandomUser at 0x22173e370d0>,
 <randomuser.RandomUser at 0x22173e37580>,
 <randomuser.RandomUser at 0x22173e377c0>,
 <randomuser.RandomUser at 0x22173e375e0>,
 <randomuser.RandomUser at 0x22173e37280>,
 <randomuser.RandomUser at 0x22173e37760>,
 <randomuser.RandomUser at 0x22173e37ee0>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [31]:
name = r.get_full_name()

We only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [32]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Lea Mitchell   lea.mitchell@example.com
Fatih Kumcuoğlu   fatih.kumcuoglu@example.com
Tea Misund   tea.misund@example.com
Bertino da Mata   bertino.damata@example.com
Julia Williams   julia.williams@example.com
Jordan Anderson   jordan.anderson@example.com
Janet Lewis   janet.lewis@example.com
Steffanie Kroezen   steffanie.kroezen@example.com
Hussein Erdal   hussein.erdal@example.com
Marc Aubert   marc.aubert@example.com

## Exercise 1
In this Exercise, generate photos of the random 10 users.

In [33]:
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/women/77.jpg
https://randomuser.me/api/portraits/men/12.jpg
https://randomuser.me/api/portraits/women/81.jpg
https://randomuser.me/api/portraits/men/55.jpg
https://randomuser.me/api/portraits/women/49.jpg
https://randomuser.me/api/portraits/men/55.jpg
https://randomuser.me/api/portraits/women/45.jpg
https://randomuser.me/api/portraits/women/52.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/men/71.jpg

In [34]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({'Name':user.get_full_name(),'Gender':user.get_gender(),'City':user.get_city(),
                      'State':user.get_state(),'Email':user.get_email(), 'DOB':user.get_dob(),
                      'Picture':user.get_picture()})
      
    return pd.DataFrame(users)

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [35]:
get_users()
df1 = pd.DataFrame(get_users())

In [36]:
df1.head()

,Name,Gender,City,State,Email,DOB,Picture
0,Becky Nguyen,female,Bristol,Central,becky.nguyen@example.com,1975-12-18T10:24:36.085Z,https://randomuser.me/api/portraits/women/35.jpg
1,Marta Lozano,female,Arrecife,Comunidad Valenciana,marta.lozano@example.com,1986-03-24T18:06:57.107Z,https://randomuser.me/api/portraits/women/93.jpg
2,Kasper Kristensen,male,Gjerlev,Midtjylland,kasper.kristensen@example.com,1972-09-19T07:01:29.051Z,https://randomuser.me/api/portraits/men/50.jpg
3,Konsta Rinne,male,Janakkala,Kymenlaakso,konsta.rinne@example.com,1954-04-06T05:12:17.449Z,https://randomuser.me/api/portraits/men/60.jpg
4,Noelle Sutton,female,Inglewood,Maine,noelle.sutton@example.com,1963-12-27T08:55:07.921Z,https://randomuser.me/api/portraits/women/79.jpg

## Example 2: Fruityvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

In [37]:
import requests
import json

We will obtain the [fruityvice](https://www.fruityvice.com) API data using the `requests.get("url")` function. To keep this lab reproducible, we request an archived snapshot of the API response. The data is in a json format.

In [38]:
data = requests.get('https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all', timeout=30)
data.raise_for_status()

We will retrieve results using json.loads() function.

In [39]:
results = json.loads(data.text)

In [40]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [41]:
df2 = pd.json_normalize(results)
df2.head()

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.2,2.6,3.9,0.9
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.1,10.0,15.0,0.4

Let's see if we can extract some information from this dataframe. Per;haps, we need to know the family and genus of a cherry.

In [42]:
cherry = df2.loc[df2['name'] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

## Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [43]:
banana = df2.loc[df2['name'] == 'Banana']
banana.iloc[0]['nutritions.calories']

96

## Exercise 3

This [page](https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/) contains a list of free public APIs for you to practice. Let us deal with the following example.

#### Official Joke API 
This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.

https://official-joke-api.appspot.com/jokes/ten

1. Using `requests.get('url')` function, load the data from the URL.

In [44]:
data2 = requests.get('https://official-joke-api.appspot.com/jokes/ten')

2. Retrieve results using json.loads() function.

In [45]:
results2 = json.loads(data2.text)

3. Convert json data into pandas data frame. Drop the type and id columns.

In [47]:
df3 = pd.DataFrame(results2)
df3.drop(columns=['type','id'],inplace=True)
df3.head()

,setup,punchline
0,Why is peter pan always flying?,Because he neverlands
1,Why did the Clydesdale give the pony a glass o...,Because he was a little horse
2,What is this movie about?,It is about 2 hours long.
3,I had a dream that I was a muffler last night.,I woke up exhausted!
4,Well...,That’s a deep subject.